FROM node:16.13-alpine

RUN mkdir /signage-monitor
WORKDIR /signage-monitor

COPY ./package.json /signage-monitor
COPY ./.npmrc /signage-monitor
COPY . /signage-monitor

RUN yarn install

RUN yarn set-env staging
RUN yarn build

CMD ["yarn", "start"]
